
CREATE FUNCTION ENTIDADE_ALEATORIA (@TIPO VARCHAR(20)) RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ENTIDADE_ALEATORIO VARCHAR(20)
	DECLARE @TABELA TABLE (CODIGO VARCHAR(20))

	DECLARE @CLIENTE_ALEATORIO VARCHAR(11)
	DECLARE @VAL_INICIAL INT
	DECLARE @VAL_FINAL INT
	DECLARE @ALEATORIO INT
	DECLARE @CONT INT

	IF @TIPO = 'CLIENTE'
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT CPF FROM [TABELA DE CLIENTES]
		END
	IF @TIPO = 'VENDEDOR'
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT MATRICULA FROM [TABELA DE VENDEDORES]
		END
	IF @TIPO = 'PRODUTO'
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS]
		END

	SET @VAL_INICIAL = 1
	SELECT @VAL_FINAL = COUNT(*) + 1 FROM @TABELA
	SET @ALEATORIO = dbo.NUMERO_ALEATORIO(@VAL_INICIAL, @VAL_FINAL)
	SET @CONT = 1

	DECLARE CURSOR1 CURSOR FOR SELECT CODIGO FROM @TABELA

	OPEN CURSOR1

	FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIO

	WHILE @CONT < @ALEATORIO
	BEGIN
		FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIO
		SET @CONT += 1
	END

	CLOSE CURSOR1
	DEALLOCATE CURSOR1

	RETURN @ENTIDADE_ALEATORIO
END

--------------------------------------------------------------------------------------------------------------

SELECT DBO.ENTIDADE_ALEATORIA('CLIENTE')
SELECT DBO.ENTIDADE_ALEATORIA('VENDEDOR')
SELECT DBO.ENTIDADE_ALEATORIA('PRODUTO')