
DECLARE @CLIENTE VARCHAR(20) -- VARIÁVEL PARA ARMAZENAR O CÓDIGO DO CLIENTE
DECLARE @VENDEDOR VARCHAR(20) -- VARIÁVEL PARA ARMAZENAR O CÓDIGO DO VENDEDOR
DECLARE @PRODUTO VARCHAR(20) -- VARIÁVEL PARA ARMAZENAR O CÓDIGO DO PRODUTO
DECLARE @DATA DATE -- VARIÁVEL PARA ARMAZENAR A DATA DA NOTA
DECLARE @NUMERO INT -- VARIÁVEL PARA ARMAZENAR O NÚMERO DA NOVA NOTA FISCAL
DECLARE @IMPOSTO FLOAT -- VARIÁVEL PARA ARMAZENAR O IMPOSTO DA NOTA
DECLARE @NUM_ITENS INT -- VARIÁVEL PARA ARMAZENAR O NUMERO DE ITENS DA NOTA
DECLARE @CONT INT -- VARIÁVEL PARA ARMAZENAR O CONTADOR DO LOOP
DECLARE @QUANTIDADE INT -- VARIÁVEL PARA ARMAZENAR A QUANTIDADE DE CADA ITEM DOS ITENS NA NOTA
DECLARE @PRECO FLOAT -- VARIÁVEL PARA ARMAZENAR O PREÇO DOS ITENSA DA NOTA
DECLARE @LISTA_PRODUTOS TABLE (PRODUTO VARCHAR(20)) -- VARIÁVEL DO TIPO TABELA PARA ARMAZENAR OS PRODUTOS JÁ ADICIONADOS
DECLARE @AUXPRODUTO INT -- VARIÁVEL PARA VERIFICAR SE O CÓDIGO DO ITEM SELECIONADO JÁ FOI USADO

SET @DATA = '2025-02-05' -- DEFINE A DATA
SET @CLIENTE = DBO.ENTIDADE_ALEATORIA('CLIENTE') -- BUSCA UM CLIENTE ALEATORIO
SET @VENDEDOR = DBO.ENTIDADE_ALEATORIA('VENDEDOR') -- BUSCA UM VENDEDOR ALEATORIO
SELECT @NUMERO = MAX(NUMERO) + 1 FROM [NOTAS FISCAIS] -- ESTABELECE O NÚMERO PARA A PRÓXIMA NOTA
SET @IMPOSTO = 0.18 -- DEFINE O VALOR DO IMPOSTO
SET @CONT = 1 -- DEFINE O CONTADOR
SET @NUM_ITENS = DBO.NUMERO_ALEATORIO(2, 10) -- NUMERO ALEATÓRIO DE ITENS DIFERENTES NA NOTA

INSERT INTO [NOTAS FISCAIS] (CPF, MATRICULA, [DATA], NUMERO, IMPOSTO)
VALUES (@CLIENTE, @VENDEDOR, @DATA, @NUMERO, @IMPOSTO) -- CRIA A NOVA NOTA FISCAL

WHILE @CONT <= @NUM_ITENS -- ENQUANTO O CONTADOR FOR <= QUE O NÚMERO DE PRODUTOS DIFERENTES NA NOTA
BEGIN
	SET @PRODUTO = DBO.ENTIDADE_ALEATORIA('PRODUTO') -- BUSCA UM PRODUTO ALEATÓRIO
	SELECT @AUXPRODUTO = COUNT(*) FROM  @LISTA_PRODUTOS WHERE PRODUTO = @PRODUTO -- VERIFICA SE O PRODUTO JÁ FOI USADO NESSA NOTA

	IF @AUXPRODUTO = 0 -- SE O PRODUTO AINDA NÃO FOI USADO NESSA NOTA
		BEGIN
			SET @QUANTIDADE = DBO.NUMERO_ALEATORIO(5, 100) -- DEFINE UMA QUANTIDADE ALEATÓRIA DESSE PRODUTO
			SELECT @PRECO = [PREÇO DE LISTA] FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = @PRODUTO -- BUSCA O PREÇO NA TABELA DE PRODUTOS
	
			INSERT INTO [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
			VALUES (@NUMERO, @PRODUTO, @QUANTIDADE, @PRECO) -- ADICIONA O NOVO ITEM CRIADO NA TABELA DE ITENS, JÁ VINCULANDO COM A NOTA

			INSERT INTO @LISTA_PRODUTOS (PRODUTO) VALUES (@PRODUTO) -- ADICIONA O PRODUTO USADO NA LISTA DE PRODUTOS JÁ UTILIZADOS NA NOTA

			SET @CONT += 1 -- INCREMENTA NO CONTADOR
		END
END