
-- ESSA FUNÇÃO GERA UMA POSIÇÃO ALEATÓRIA EM UMA TABELA INFORMADA COMO PARÂMETRO PARA JUNTARMOS DADOS ALEATÓRIOS PARA CRIAÇÃO DE NOVAS NOTAS FISCAIS

CREATE FUNCTION ENTIDADE_ALEATORIA (@TIPO VARCHAR(20)) RETURNS VARCHAR(20) -- CRIANDO FUNÇÃO (VARIÁVEL TIPO: INFORMA A ENTIDADE QUE SERÁ GERADA)
AS
BEGIN
	DECLARE @ENTIDADE_ALEATORIO VARCHAR(20) -- VARIÁVEL PARA ARMAZENAR O ID DA ENTIDADE
	DECLARE @TABELA TABLE (CODIGO VARCHAR(20)) -- VARIÁVEL DO TIPO TABELA

	DECLARE @VAL_INICIAL INT -- VALOR ALEATÓRIO INICIAL
	DECLARE @VAL_FINAL INT -- VALOR ALEATÓRIO FINAL
	DECLARE @ALEATORIO INT -- NÚMERO ALEATÓRIO GERADO
	DECLARE @CONT INT -- CONTADOR

	IF @TIPO = 'CLIENTE' -- SE O TIPO FOR CLIENTE
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT CPF FROM [TABELA DE CLIENTES] -- INSERE A CONSULTA DE CLIENTES NA VARIÁVEL DE TABELA
		END
	IF @TIPO = 'VENDEDOR' -- SE O TIPO FOR VENDEDOR
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT MATRICULA FROM [TABELA DE VENDEDORES] -- INSERE A CONSULTA DE VENDEDORES NA VARIÁVEL DE TABELA
		END
	IF @TIPO = 'PRODUTO' -- SE O TIPO FOR CLIENTE
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS] -- INSERE A CONSULTA DE PRODUTOS NA VARIÁVEL DE TABELA
		END

	SET @VAL_INICIAL = 1 -- VALOR INICIAL PARA ALEATÓRIO COMEÇA EM 1
	SELECT @VAL_FINAL = COUNT(*) + 1 FROM @TABELA -- VALOR FINAL É IGUAL A QUANTIDADE DE REGISTROS NA VARIÁVEL DE TABELA + 1 PRA AJUSTAR
	SET @ALEATORIO = dbo.NUMERO_ALEATORIO(@VAL_INICIAL, @VAL_FINAL) -- GERA O NÚMERO ALEATÓRIO USANDO A FUNÇÃO CRIADA
	SET @CONT = 1 -- CONTADOR COMEÇA EM 1

	DECLARE CURSOR1 CURSOR FOR SELECT CODIGO FROM @TABELA -- DECLARA O CURSOR COMO A CONSULTA DA VARIÁVEL DE TABELA

	OPEN CURSOR1 -- ABRE O CURSOR

	FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIO -- VERIFICA O PRIMEIRO REGISTRO

	WHILE @CONT < @ALEATORIO -- ENQUANTO O CONTADOR FOR MENOR DO QUE O NÚMERO ALEATÓRIO
	BEGIN
		FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIO -- VAI PARA O PRÓXIMO REGISTRO
		SET @CONT += 1 -- INCREMENTA NO CONTADOR
	END

	CLOSE CURSOR1 -- FECHA O CURSOR
	DEALLOCATE CURSOR1 -- DELETA O CURSOR

	RETURN @ENTIDADE_ALEATORIO -- RETORNA O IDENTIFICADOR ALEATÓRIO PARA ENTIDADE SOLICITADA
END

--------------------------------------------------------------------------------------------------------------

SELECT DBO.ENTIDADE_ALEATORIA('CLIENTE')
SELECT DBO.ENTIDADE_ALEATORIA('VENDEDOR')
SELECT DBO.ENTIDADE_ALEATORIA('PRODUTO')