SELECT
	TB_C.CPF,
	TB_C.NOME,
	FORMAT(TB_N.[DATA], 'MMMM', 'pt-BR') AS MES,
	FORMAT(TB_N.[DATA], 'yyyy') AS ANO,
	TB_C.[VOLUME DE COMPRA],
	SUM(TB_I.QUANTIDADE) AS QUANTIDADE,
	CASE 
		WHEN SUM(TB_I.QUANTIDADE) > TB_C.[VOLUME DE COMPRA] THEN 'COMPRA INVÁLIDA' 
		ELSE 'COMPRA VÁLIDA' 
	END AS VERIFICADOR 
FROM 
	[TABELA DE CLIENTES] TB_C 
INNER JOIN 
	[NOTAS FISCAIS] TB_N ON TB_C.CPF = TB_N.CPF
INNER JOIN [ITENS NOTAS FISCAIS] TB_I ON TB_N.NUMERO = TB_I.NUMERO
GROUP BY 
	FORMAT(TB_N.[DATA], 'MMMM', 'pt-BR'),
	DATENAME(MONTH, TB_N.[DATA]),
	TB_C.CPF, TB_C.NOME,
	TB_C.[VOLUME DE COMPRA],
	TB_N.[DATA]
ORDER BY 
	NOME,
	TB_N.[DATA]