SELECT
	PROD.SABOR,
	YEAR(NF.[DATA]) AS ANO,
	CAST(SUM(ITEM.[PREÇO] * ITEM.QUANTIDADE) AS DECIMAL(15, 2)) AS FATURAMENTO,
	CONCAT(CAST(SUM(ITEM.[PREÇO] * ITEM.QUANTIDADE) / (SELECT FATURAMENTO FROM VW_FATURAMENTO_TOTAL_2016) * 100 AS DECIMAL(5, 2)), '%') AS PORCENTAGEM
FROM
	[TABELA DE PRODUTOS] PROD 
INNER JOIN [ITENS NOTAS FISCAIS] ITEM
	ON PROD.[CODIGO DO PRODUTO] = ITEM.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
	ON NF.NUMERO = ITEM.NUMERO
WHERE 
	YEAR(NF.[DATA]) = 2016
GROUP BY 
	PROD.SABOR,
	YEAR(NF.[DATA])
ORDER BY
	FATURAMENTO DESC